### ISSUE TITLE
Create working localhost example

### ISSUE THREAD

**Issue by brucetony** [PrivateAIM/helm#12]
Need to develop an example `values_min.yaml` that works on a local installation without a FQDN i.e. purely with port forwarding

**Comment by brucetony** [comment]
Simplest example:
```yaml
global:
  hub:
    auth:
      robotUser: "<some uuid>"
      robotSecret: "<some secret>"
  node:
    ingress:
      enabled: false
      hostname: ""
```
