### ISSUE TITLE
Missing existingSecret options

### ISSUE THREAD

**Issue by bauerjs1** [PrivateAIM/helm#13]
Hi there

Kudos to you providing a Helm chart for the PrivateAIM node! 🙏🏻 We are currently trying to deploy in an existing Kubernetes cluster with ArgoCD and there are a couple of minor pitfalls that I'm gonna raise issues about here.

One thing is the secret management. Since with GitOps, you don't want to hard code secret values in your Helm values files, we must be able to reference existing secrets (in our case we use ExternalSecretsOperator for those but it doesn't really matter here).

Now actually, this workflow is already implemented, except from these three places in the stack:
- `node-message-broker-deployment.yml` hard-codes the secret value in the deployment spec instead of referencing the correct secret
- `node-message-broker-hub-auth-secret.yml` requires a secret value specified in the Helm values
- `node-result-hub-auth-secret.yml` does not seem to be used anywhere but it also requires a secret value specified in the Helm values

It would also be convenient to be able to specify the key of the robot secret in the `existingSecret` (but that's just nice-to-have)

**Comment by brucetony** [comment]
@bauerjs1 Moved your issue to this repo since this is where the action is now. I divided your comments into sub-tasks and we get to those ASAP

**Comment by bauerjs1** [comment]
@brucetony with the chart version `0.0.5` I still need to provide some private key as plain text file. The chart won't render and fails with
> Required file ./private_key.pem is missing! Please generate one using the 'Crypto' tab in the Hub for your node

We should be able to reference an existing secret for this as well. I tried to provide a dummy file for testing but it turns out this isn't even possible:
> Files outside of a Helm application subchart, including those of the parent, cannot be accessed [[Helm docs](https://helm.sh/docs/chart_template_guide/accessing_files/)]

To give you some context: With GitOps it is very common to deploy apps as subcharts in a so-called "umbrella chart". That's how we're deploying the `flame-node`, too. It looks something like this:
```yaml
# Chart.yaml:
apiVersion: v2
name: flame
version: 1.0.0
dependencies:
  - name: external-secrets # some internal convenience chart for importing secrets
    repository: oci://harbor.diz.uk-erlangen.de/charts
    version: 1.0.3
  - name: flame-node
    repository: https://PrivateAIM.github.io/helm
    version: 0.0.5
---
# values.yaml:
external-secrets:
  secrets:
    - name: robot-credentials
      vault:
        path: foo/flame/robot
    - name: oidc
      vault:
        path: foo/flame/oidc
global:
  hub:
    auth:
      existingSecret: robot-credentials
flame-node:
  flame-node-ui: # ...
  flame-node-hub-adapter: # ...
  flame-node-result-service: # ...
  # ...
```

Since everything is a subchart, we cannot pass them any files
